from kafka.coordinator.assignors.range import RangePartitionAssignor
from kafka.coordinator.assignors.roundrobin import RoundRobinPartitionAssignor
import socket

DEFAULT_CONFIG = {
    'bootstrap_servers': 'localhost',
    'client_id': 'kafka-python-' + '3',
    'group_id': None,
    'key_deserializer': None,
    'value_deserializer': None,
    'fetch_max_wait_ms': 500,
    'fetch_min_bytes': 1,
    'fetch_max_bytes': 52428800,
    'max_partition_fetch_bytes': 1 * 1024 * 1024,
    'request_timeout_ms': 40 * 1000,
    'retry_backoff_ms': 100,
    'reconnect_backoff_ms': 50,
    'reconnect_backoff_max_ms': 1000,
    'max_in_flight_requests_per_connection': 5,
    'auto_offset_reset': 'latest',
    'enable_auto_commit': True,
    'auto_commit_interval_ms': 5000,
    'default_offset_commit_callback': lambda offsets, response: True,
    'check_crcs': True,
    'metadata_max_age_ms': 5 * 60 * 1000,
    'partition_assignment_strategy': (RangePartitionAssignor, RoundRobinPartitionAssignor),
    'heartbeat_interval_ms': 3000,
    'session_timeout_ms': 30000,
    'max_poll_records': 500,
    'receive_buffer_bytes': None,
    'send_buffer_bytes': None,
    'socket_options': [(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)],
    'consumer_timeout_ms': float('inf'),
    'skip_double_compressed_messages': False,
    'security_protocol': 'PLAINTEXT',
    'ssl_context': None,
    'ssl_check_hostname': True,
    'ssl_cafile': None,
    'ssl_certfile': None,
    'ssl_keyfile': None,
    'ssl_crlfile': None,
    'ssl_password': None,
    'api_version': None,
    'api_version_auto_timeout_ms': 2000,
    'connections_max_idle_ms': 9 * 60 * 1000,
    'metric_reporters': [],
    'metrics_num_samples': 2,
    'metrics_sample_window_ms': 30000,
    'metric_group_prefix': 'consumer',
    'selector': selectors.DefaultSelector,
    'exclude_internal_topics': True,
    'sasl_mechanism': None,
    'sasl_plain_username': None,
    'sasl_plain_password': None,
}
